"""
maxwell.crypto — TEE (Trusted Execution Environment) Simulator

Provides cryptographic proof of compute (PoC) by generating an Ethereum-compatible
ECDSA signature over the completed task's actual FLOPs.
"""

from __future__ import annotations

import logging
from typing import NamedTuple

from eth_account import Account
from eth_account.messages import encode_defunct
from web3 import Web3

logger = logging.getLogger("maxwell.crypto")

class TEESignature(NamedTuple):
    public_key: str
    flops_actual: int
    signature_hex: str


class TEESimulator:
    """
    Simulates a hardware Trusted Execution Environment (e.g., Intel SGX / AWS Nitro).
    
    Upon initialization, it generates a fresh, ephemeral Ethereum keypair.
    In a real implementation, this key would be securely generated inside an enclave
    and remotely attested to the smart contract.
    """

    def __init__(self) -> None:
        # Enable unprotected HD wallet features
        Account.enable_unaudited_hdwallet_features()
        
        # Generate a new random Ethereum account acting as the TEE hardware identity
        self._account = Account.create()
        self.public_address = self._account.address
        logger.info(f"TEE Simulator initialized. Public Address: {self.public_address}")

    def sign_execution(self, task_id: int, flops_actual: int) -> TEESignature:
        """
        Cryptographically attest to the computation.
        
        We sign the equivalent of `keccak256(abi.encodePacked(taskId, flopsActual))`
        so the Solidity contract can verify it via `ecrecover`.
        """
        # Pack the data exactly as Solidity's abi.encodePacked(uint256, uint256)
        packed_data = Web3.solidity_keccak(
            ['uint256', 'uint256'],
            [task_id, flops_actual]
        )
        
        # In Ethereum, signatures are typically prefixed with "\x19Ethereum Signed Message:\n32"
        # encode_defunct does exactly this.
        message = encode_defunct(packed_data)
        
        # Sign the message
        signed_message = self._account.sign_message(message)
        
        return TEESignature(
            public_key=self.public_address,
            flops_actual=flops_actual,
            signature_hex="0x" + signed_message.signature.hex()
        )

    @classmethod
    def verify_execution(cls, public_key: str, task_id: int, flops_actual: int, signature_hex: str) -> bool:
        """
        Verify the TEE signature generated by a provider.
        """
        packed_data = Web3.solidity_keccak(
            ['uint256', 'uint256'],
            [task_id, flops_actual]
        )
        message = encode_defunct(packed_data)
        try:
            recovered_address = Account.recover_message(message, signature=signature_hex)
            return bool(recovered_address.lower() == public_key.lower())
        except Exception as e:
            logger.error("Failed to recover TEE signature: %s", e)
            return False
