"""
maxwell.crypto — TEE (Trusted Execution Environment) Simulator

Provides cryptographic proof of compute (PoC) by generating an Ethereum-compatible
ECDSA signature over the completed task's actual FLOPs.
"""

from __future__ import annotations

import logging
from typing import NamedTuple

from eth_account import Account
from eth_account.messages import encode_defunct
from web3 import Web3

logger = logging.getLogger("maxwell.crypto")

# Expected enclave hash for Maxwell Provider (mock)
EXPECTED_MRENCLAVE = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

class TEEQuote(NamedTuple):
    public_key: str
    flops_actual: int
    signature_hex: str
    mrenclave: str
    certificate_chain: list[str]


class TEESimulator:
    """
    Simulates a hardware Trusted Execution Environment (e.g., Intel SGX / AWS Nitro).
    
    Upon initialization, it generates a fresh, ephemeral Ethereum keypair.
    In a real implementation, this key would be securely generated inside an enclave
    and remotely attested to the smart contract.
    """

    def __init__(self) -> None:
        # Enable unprotected HD wallet features
        Account.enable_unaudited_hdwallet_features()
        
        # Generate a new random Ethereum account acting as the TEE hardware identity
        self._account = Account.create()
        self.public_address = self._account.address
        logger.info(f"TEE Simulator initialized. Public Address: {self.public_address}")

    def sign_execution(self, task_id: int, flops_actual: int) -> TEEQuote:
        """
        Cryptographically attest to the computation.
        
        We sign the equivalent of `keccak256(abi.encodePacked(taskId, flopsActual))`
        so the Solidity contract can verify it via `ecrecover`.
        Includes MRENCLAVE and X.509 certs simulating Intel SGX DCAP / AWS Nitro.
        """
        # Pack the data exactly as Solidity's abi.encodePacked(uint256, uint256)
        packed_data = Web3.solidity_keccak(
            ['uint256', 'uint256'],
            [task_id, flops_actual]
        )
        
        # In Ethereum, signatures are typically prefixed with "\x19Ethereum Signed Message:\n32"
        # encode_defunct does exactly this.
        message = encode_defunct(packed_data)
        
        # Sign the message
        signed_message = self._account.sign_message(message)
        
        # Generate mock certificate chain (Root CA -> Intermediate -> Enclave)
        cert_chain = [
            "-----BEGIN CERTIFICATE-----\nROOT_CA_MOCK\n-----END CERTIFICATE-----",
            "-----BEGIN CERTIFICATE-----\nINT_CA_MOCK\n-----END CERTIFICATE-----",
            f"-----BEGIN CERTIFICATE-----\nENCLAVE_{self.public_address}\n-----END CERTIFICATE-----"
        ]
        
        return TEEQuote(
            public_key=self.public_address,
            flops_actual=flops_actual,
            signature_hex="0x" + signed_message.signature.hex(),
            mrenclave=EXPECTED_MRENCLAVE,
            certificate_chain=cert_chain
        )

    @classmethod
    def verify_execution(cls, quote: TEEQuote, task_id: int) -> bool:
        """
        Verify the TEE quote generated by a provider.
        Validates MRENCLAVE, certificate chain trust, and ECDSA signature.
        """
        # 1. Verify MRENCLAVE (Code Integrity)
        if quote.mrenclave != EXPECTED_MRENCLAVE:
            logger.error("MRENCLAVE mismatch. Enclave code may have been tampered with.")
            return False
            
        # 2. Verify X.509 Certificate Chain (Hardware Trust)
        if len(quote.certificate_chain) != 3 or "ROOT_CA_MOCK" not in quote.certificate_chain[0]:
            logger.error("Invalid Intel SGX / Nitro certificate chain.")
            return False
            
        # 3. Verify ECDSA signature of the execution metrics
        packed_data = Web3.solidity_keccak(
            ['uint256', 'uint256'],
            [task_id, quote.flops_actual]
        )
        message = encode_defunct(packed_data)
        try:
            recovered_address = Account.recover_message(message, signature=quote.signature_hex)
            return bool(recovered_address.lower() == quote.public_key.lower())
        except Exception as e:
            logger.error("Failed to recover TEE signature: %s", e)
            return False
